### PR TITLE
Add SSM reference feature

### PR DESCRIPTION
**Pull request by kotowick**
This feature looks through the values that contain `ssm://` as a reference. If it does, it then makes a request for that parameter. 

If then merges the values from the referenced version into the requested version.

### CODE REVIEW

**Comment by Sjeanpierre** [comment]
What happens if the ref does not actually exist?

**Comment by kotowick** [comment]
@Sjeanpierre code updated - if a ssm:// param key is missing, then it returns an empty body. In this case, the app will not start.

If the SSM parameter reference exists, but it is missing a sub key in the json data, it will also return an empty body.

**Comment by Sjeanpierre** [comment]
@kotowick should we be more explicit with this at all? like make sure we are logging strong exceptions

**Comment by kotowick** [comment]
Logs when everything is successful:
screen shot 2018-08-14 at 1 37 37 pm

Logs when a parameter reference does not exist in SSM
screen shot 2018-08-14 at 1 36 47 pm

Logs when the parameter reference exists in SSM, but the expected KEY in the parameter doesn’t exist
screen shot 2018-08-14 at 1 37 19 pm

**Pull request merged**
